<?php
echo "<h1>All Products</h1>";
if ($products->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Tags</th>
                <th>Stock</th>
                <th>Action</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Product quantity: <?php echo $products->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($products as $products) { ?>
                <tr>
                    <td><?php echo $products->id; ?></td>
                    <td><?php echo $products->name; ?></td>
                    <td><?php echo $products->price; ?></td>
                    <td><?php echo $products->description; ?></td>
                    <td><?php echo $products->tags; ?></td>
                    <td><?php echo $products->stock; ?></td>
                    <td><?php echo "<a href = 'delete/$products->id'>delete</a>"; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php
}
