<?php
echo "<h1>All users</h1>";
if ($users->count() > 0) {
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Product quantity: <?php echo $users->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($users as $users) { ?>
                <tr>
                    <td><?php echo $users->id; ?></td>
                    <td><?php echo $users->name; ?></td>
                    <td><?php echo $users->email; ?></td>
                    <td><?php echo $users->role; ?></td>
                    <td><?php echo "<a href = 'delete/$users->id'>delete</a>"; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php
}
